#pragma once

#define NPPTERMINAL_VERSION_MAJOR 0
#define NPPTERMINAL_VERSION_MINOR 3
#define NPPTERMINAL_VERSION_PATCH 26
#define NPPTERMINAL_VERSION_STRING "0.3.26"
#define NPPTERMINAL_VERSION_FILE_COMMA 0,3,26,0
