#pragma once

#define NPPTERMINAL_VERSION_MAJOR 0
#define NPPTERMINAL_VERSION_MINOR 5
#define NPPTERMINAL_VERSION_PATCH 0
#define NPPTERMINAL_VERSION_STRING "0.5.0"
#define NPPTERMINAL_VERSION_FILE_COMMA 0,5,0,0
